export const categories = {
    "data": {
        "categoryArray": [
            {
                "categoryIdentifier": "LivingRoom",
                "categoryName": "Living Room",
                "uniqueID": "3074457345616678418",
                "categoryHref": "",
                "thumbnail": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/dep_livingroom.jpg",
                "longDescription": "",
                "columns": 3,
                "displaySkus": false,
                "pageTitle": "",
                "imageAltText": "",
                "metaDescription": "",
                "startPrice": "",
                "productCount": "",
                "seoId": "living-room",
                "isTopLevelCategory": false,
                "parentCategoryId": "-1",
                "isLeafNode": "N",
                "subCategoryArray": [
                    {
                        "categoryIdentifier": "LivingRoomFurniture",
                        "categoryName": "Furniture",
                        "uniqueID": "3074457345616678419",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/furniture.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/furniture.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "furniture",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678418",
                        "parentCategoryName": "Living Room",
                        "isLeafNode": "Y",
                        "topCategoryName": "Living Room",
                        "topCategoryIdentifier": "LivingRoom",
                        "topSeoHref": "furniture",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "LivingRoomLighting",
                        "categoryName": "Lighting",
                        "uniqueID": "3074457345616678420",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/livingroom-lighting.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/livingroom-lighting.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "lighting-livingroomlighting",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678418",
                        "parentCategoryName": "Living Room",
                        "isLeafNode": "Y",
                        "topCategoryName": "Living Room",
                        "topCategoryIdentifier": "LivingRoom",
                        "topSeoHref": "lighting-livingroomlighting",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "Decoration",
                        "categoryName": "Decoration",
                        "uniqueID": "3074457345616678421",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/decoration.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/livingroom/category/decoration.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "decoration",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678418",
                        "parentCategoryName": "Living Room",
                        "isLeafNode": "Y",
                        "topCategoryName": "Living Room",
                        "topCategoryIdentifier": "LivingRoom",
                        "topSeoHref": "decoration",
                        "contentUrl": ""
                    }
                ],
                "contentUrl": "",
                "marketingCategories": {
                    "title": "",
                    "categoryList": []
                }
            },
            {
                "categoryIdentifier": "Bath",
                "categoryName": "Bath",
                "uniqueID": "3074457345616678426",
                "categoryHref": "",
                "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/dep_bathroom.jpg",
                "longDescription": "",
                "columns": 3,
                "displaySkus": false,
                "pageTitle": "",
                "imageAltText": "",
                "metaDescription": "",
                "startPrice": "",
                "productCount": "",
                "seoId": "bath",
                "isTopLevelCategory": false,
                "parentCategoryId": "-1",
                "isLeafNode": "N",
                "subCategoryArray": [
                    {
                        "categoryIdentifier": "BathLighting",
                        "categoryName": "Lighting",
                        "uniqueID": "3074457345616678427",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/lighting.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/lighting.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "lighting",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678426",
                        "parentCategoryName": "Bath",
                        "isLeafNode": "Y",
                        "topCategoryName": "Bath",
                        "topCategoryIdentifier": "Bath",
                        "topSeoHref": "lighting",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "Fixtures",
                        "categoryName": "Fixtures",
                        "uniqueID": "3074457345616678428",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/fixtures.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/fixtures.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "fixtures",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678426",
                        "parentCategoryName": "Bath",
                        "isLeafNode": "Y",
                        "topCategoryName": "Bath",
                        "topCategoryIdentifier": "Bath",
                        "topSeoHref": "fixtures",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "Accessories",
                        "categoryName": "Accessories",
                        "uniqueID": "3074457345616678429",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/accessories.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/bathroom/category/accessories.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "accessories",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678426",
                        "parentCategoryName": "Bath",
                        "isLeafNode": "Y",
                        "topCategoryName": "Bath",
                        "topCategoryIdentifier": "Bath",
                        "topSeoHref": "accessories",
                        "contentUrl": ""
                    }
                ],
                "contentUrl": "",
                "marketingCategories": {
                    "title": "",
                    "categoryList": []
                }
            },
            {
                "categoryIdentifier": "Bedroom",
                "categoryName": "Bedroom",
                "uniqueID": "3074457345616678430",
                "categoryHref": "",
                "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bedroom/category/dep_bedroom.jpg",
                "longDescription": "",
                "columns": 3,
                "displaySkus": false,
                "pageTitle": "",
                "imageAltText": "",
                "metaDescription": "",
                "startPrice": "",
                "productCount": "",
                "seoId": "bedroom",
                "isTopLevelCategory": false,
                "parentCategoryId": "-1",
                "isLeafNode": "N",
                "subCategoryArray": [
                    {
                        "categoryIdentifier": "Beds",
                        "categoryName": "Beds",
                        "uniqueID": "3074457345616678431",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bedroom/category/beds.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/bedroom/category/beds.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "beds",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678430",
                        "parentCategoryName": "Bedroom",
                        "isLeafNode": "Y",
                        "topCategoryName": "Bedroom",
                        "topCategoryIdentifier": "Bedroom",
                        "topSeoHref": "beds",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "Dressers",
                        "categoryName": "Dressers",
                        "uniqueID": "3074457345616678432",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/bedroom/category/dressers.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/bedroom/category/dressers.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "dressers",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678430",
                        "parentCategoryName": "Bedroom",
                        "isLeafNode": "Y",
                        "topCategoryName": "Bedroom",
                        "topCategoryIdentifier": "Bedroom",
                        "topSeoHref": "dressers",
                        "contentUrl": ""
                    }
                ],
                "contentUrl": "",
                "marketingCategories": {
                    "title": "",
                    "categoryList": []
                }
            },
            {
                "categoryIdentifier": "DiningRoom",
                "categoryName": "Dining Room",
                "uniqueID": "3074457345616678422",
                "categoryHref": "",
                "thumbnail": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/dep_diningroom.jpg",
                "longDescription": "",
                "columns": 3,
                "displaySkus": false,
                "pageTitle": "",
                "imageAltText": "",
                "metaDescription": "",
                "startPrice": "",
                "productCount": "",
                "seoId": "dining-room",
                "isTopLevelCategory": false,
                "parentCategoryId": "-1",
                "isLeafNode": "N",
                "subCategoryArray": [
                    {
                        "categoryIdentifier": "DiningTables",
                        "categoryName": "Tables",
                        "uniqueID": "3074457345616678423",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/tables.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/tables.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "tables",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678422",
                        "parentCategoryName": "Dining Room",
                        "isLeafNode": "Y",
                        "topCategoryName": "Dining Room",
                        "topCategoryIdentifier": "DiningRoom",
                        "topSeoHref": "tables",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "DiningChairs",
                        "categoryName": "Chairs",
                        "uniqueID": "3074457345616678424",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/chairs.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/chairs.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "chairs",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678422",
                        "parentCategoryName": "Dining Room",
                        "isLeafNode": "Y",
                        "topCategoryName": "Dining Room",
                        "topCategoryIdentifier": "DiningRoom",
                        "topSeoHref": "chairs",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "Buffets",
                        "categoryName": "Buffets",
                        "uniqueID": "3074457345616678425",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/buffets.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/diningroom/category/buffets.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "buffets",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678422",
                        "parentCategoryName": "Dining Room",
                        "isLeafNode": "Y",
                        "topCategoryName": "Dining Room",
                        "topCategoryIdentifier": "DiningRoom",
                        "topSeoHref": "buffets",
                        "contentUrl": ""
                    }
                ],
                "contentUrl": "",
                "marketingCategories": {
                    "title": "",
                    "categoryList": []
                }
            },
            {
                "categoryIdentifier": "Kitchen",
                "categoryName": "Kitchen",
                "uniqueID": "3074457345616678433",
                "categoryHref": "",
                "thumbnail": "/hclstore/Oslo1CAS/images/catalog/kitchen/category/dep_kitchen.jpg",
                "longDescription": "",
                "columns": 3,
                "displaySkus": false,
                "pageTitle": "",
                "imageAltText": "",
                "metaDescription": "",
                "startPrice": "",
                "productCount": "",
                "seoId": "kitchen",
                "isTopLevelCategory": false,
                "parentCategoryId": "-1",
                "isLeafNode": "N",
                "subCategoryArray": [
                    {
                        "categoryIdentifier": "Cabinets",
                        "categoryName": "Cabinets",
                        "uniqueID": "3074457345616678434",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/kitchen/category/cabinets.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/kitchen/category/cabinets.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "cabinets",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678433",
                        "parentCategoryName": "Kitchen",
                        "isLeafNode": "Y",
                        "topCategoryName": "Kitchen",
                        "topCategoryIdentifier": "Kitchen",
                        "topSeoHref": "cabinets",
                        "contentUrl": ""
                    },
                    {
                        "categoryIdentifier": "Countertops",
                        "categoryName": "Countertops",
                        "uniqueID": "3074457345616678435",
                        "categoryHref": "",
                        "thumbnail": "/hclstore/Oslo1CAS/images/catalog/kitchen/category/countertops.jpg",
                        "fullImage": "/hclstore/Oslo1CAS/images/catalog/kitchen/category/countertops.jpg",
                        "longDescription": "",
                        "columns": 3,
                        "displaySkus": false,
                        "pageTitle": "",
                        "imageAltText": "",
                        "metaDescription": "",
                        "startPrice": "",
                        "productCount": "",
                        "seoId": "countertops",
                        "isTopLevelCategory": false,
                        "parentCategoryId": "3074457345616678433",
                        "parentCategoryName": "Kitchen",
                        "isLeafNode": "Y",
                        "topCategoryName": "Kitchen",
                        "topCategoryIdentifier": "Kitchen",
                        "topSeoHref": "countertops",
                        "contentUrl": ""
                    }
                ],
                "contentUrl": "",
                "marketingCategories": {
                    "title": "",
                    "categoryList": []
                }
            }
        ],
        "megamenu": {
            "footer": null
        }
    }
}